set -g prefix C-w
set -g mouse on
set -g set-clipboard on

set -g status-position top
set -g base-index 1
set -g renumber-windows on

bind '=' split-window -c "#{pane_current_path}"
bind '"' split-window -h -c "#{pane_current_path}"

bind x kill-pane
bind g run "~/.config/scripts/open_github.sh"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'rose-pine/tmux'

set -g @rose_pine_variant 'dawn'
set -g @rose_pine_directory 'on'
set -g @rose_pine_bar_bg_disable 'on'
set -g @rose_pine_disable_active_window_menu 'on'
set -g @rose_pine_status_left_prepend_section '#{?client_prefix,#[bg=#B893E1#,fg=#faf4ed],#[bg=default]}'

run '~/.config/tmux/plugins/tpm/tpm'
